package gui;

import Utils.Utils;
import conexion.ConexionSqlite;
import entidades.Persona;
import implementacion.ImplPersona;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Agregar extends javax.swing.JInternalFrame {
    DefaultTableModel modelo;

    
    public Agregar() {
        initComponents();
        
            
        jTextField_person_id.setVisible(false);
        
        ConexionSqlite cnx = new ConexionSqlite();
                
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellido paterno");
        modelo.addColumn("Apellido materno");
        modelo.addColumn("Direccion");
        modelo.addColumn("Correo");
        modelo.addColumn("Numero de celular");
        modelo.addColumn("Años de edad");
        modelo.addColumn("DNI");
        modelo.addColumn("Nivel de educacion");
        modelo.addColumn("Estado civil");
        modelo.addColumn("Genero");
        modelo.addColumn("Usuario");
        modelo.addColumn("Contraseña");
        this.jTable1_reporte.setModel(modelo);
        
        
       
        try {
           Statement st = cnx.getConnect().createStatement();
           String query = "select * from personas";
           ResultSet rs = st.executeQuery(query);
           
           
           while(rs.next()){
           Persona p = new Persona();
           
           p.setId(rs.getString("PER_ID"));
           p.setNombres(rs.getString(2));
           p.setApellido_pater(rs.getString(3));
           p.setApellido_mater(rs.getString(4));
           p.setDireccion(rs.getString(5));
           p.setCorreo(rs.getString(6));
           p.setNum_celular(rs.getString(7));
           p.setAnios_edad(rs.getString(8));
           p.setDni(rs.getString(9));
           p.setNivel_educacion(rs.getObject(10));
           p.setEstado_civil(rs.getObject(11));
           p.setGenero(rs.getObject(12));
           p.setUsuario(rs.getString(13));
           p.setContrasenia(rs.getString(14));
           
        String info[] = new String[14];
        info[0]= p.getId();
        info[1]= p.getNombres();
        info[2]= p.getApellido_pater();
        info[3]= p.getApellido_mater();
        info[4]= p.getDireccion();
        info[5]= p.getCorreo();
        info[6]= p.getNum_celular();
        info[7]= p.getAnios_edad();
        info[8]= p.getDni();
        info[9]= ""+p.getNivel_educacion();
        info[10]= ""+p.getEstado_civil();
        info[11]= ""+p.getGenero();
        info[12]=p.getUsuario();
        info[13]= "********";//p.getContrasenia();
        modelo.addRow(info);
           
         
           
           }
           
     
        } catch (SQLException ex) {
            Logger.getLogger(ImplPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_titulo = new javax.swing.JLabel();
        jLabel1_nombres = new javax.swing.JLabel();
        jTextField1_nombres = new javax.swing.JTextField();
        jLabel1_apellpater = new javax.swing.JLabel();
        jTextField_apellpater = new javax.swing.JTextField();
        jLabel_apellmater = new javax.swing.JLabel();
        jTextField_apellmater = new javax.swing.JTextField();
        jLabel_direccion = new javax.swing.JLabel();
        jTextField_direccion = new javax.swing.JTextField();
        jLabel_correo = new javax.swing.JLabel();
        jTextField_correo = new javax.swing.JTextField();
        jLabel_numero_celular = new javax.swing.JLabel();
        jTextField_numero_celular = new javax.swing.JTextField();
        jLabel_anios_edad = new javax.swing.JLabel();
        jTextField_anios_edad = new javax.swing.JTextField();
        jLabel_numero_dni = new javax.swing.JLabel();
        jTextField_numero_dni = new javax.swing.JTextField();
        jLabel_usuario = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jLabel_contrasenia = new javax.swing.JLabel();
        jPasswordField_contrasenia = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_nivel_educacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_estado_civil = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_genero = new javax.swing.JComboBox<>();
        jButton_grabar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_reporte = new javax.swing.JTable();
        jButton_Limpiar_AgregarPersonas = new javax.swing.JButton();
        jTextField_person_id = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agregar personas");

        jLabel1_titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1_titulo.setText("Agregar Personas");

        jLabel1_nombres.setText("Nombres:");

        jLabel1_apellpater.setText("Apellido Paterno:");

        jLabel_apellmater.setText("Apellido Materno:");

        jLabel_direccion.setText("Direccion:");

        jLabel_correo.setText("Correo:");

        jLabel_numero_celular.setText("Numero de celular:");

        jLabel_anios_edad.setText("Años de edad:");

        jLabel_numero_dni.setText("Numero de DNI:");

        jLabel_usuario.setText("Usuario:");

        jLabel_contrasenia.setText("Contraseña:");

        jLabel1.setText("Nivel de educación:");

        jComboBox_nivel_educacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inicial", "Primario", "Secundario", "Superior" }));

        jLabel2.setText("Estado civil:");

        jComboBox_estado_civil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Viudo", "Divorciado" }));

        jLabel3.setText("Género:");

        jComboBox_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Prefiero no decirlo" }));

        jButton_grabar.setText("Grabar");
        jButton_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_grabarActionPerformed(evt);
            }
        });

        jTable1_reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14"
            }
        ));
        jTable1_reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_reporteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_reporte);

        jButton_Limpiar_AgregarPersonas.setText("Limpiar");
        jButton_Limpiar_AgregarPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Limpiar_AgregarPersonasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton_Limpiar_AgregarPersonas)
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1_nombres)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField1_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1_apellpater)
                                                .addComponent(jLabel_apellmater)
                                                .addComponent(jLabel_direccion)
                                                .addComponent(jLabel_correo)
                                                .addComponent(jLabel_numero_celular)
                                                .addComponent(jLabel_anios_edad)
                                                .addComponent(jLabel_numero_dni)
                                                .addComponent(jLabel_usuario)
                                                .addComponent(jLabel_contrasenia))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField_person_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_numero_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_apellmater, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_apellpater, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_anios_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_numero_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPasswordField_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(337, 337, 337)
                                .addComponent(jButton_grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_estado_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_nivel_educacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(535, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1_titulo)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton_Limpiar_AgregarPersonas)
                                .addGap(32, 32, 32)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1_nombres)
                            .addComponent(jTextField1_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox_nivel_educacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1_apellpater)
                            .addComponent(jTextField_apellpater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_apellmater)
                            .addComponent(jTextField_apellmater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_direccion)
                            .addComponent(jTextField_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_correo)
                            .addComponent(jTextField_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox_estado_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_numero_celular)
                            .addComponent(jTextField_numero_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_anios_edad)
                            .addComponent(jTextField_anios_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_numero_dni)
                            .addComponent(jTextField_numero_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_usuario)
                    .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_contrasenia)
                    .addComponent(jPasswordField_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_grabar)
                    .addComponent(jTextField_person_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_grabarActionPerformed

        ImplPersona ip= new ImplPersona();
        Persona p = new Persona();
        Utils ge = new Utils();

        //System.out.print("Nombres"+jTextField1_nombres.getText());
        //System.out.print("Apellidos"+jTextField_apellpater.getText());

        if(jTextField1_nombres.getText().equals("")||
           jTextField_apellpater.getText().equals("")||
           jTextField_apellmater.getText().equals("")||
           jTextField_direccion.getText().equals("")||
           jTextField_correo.getText().equals("")||
           jTextField_numero_celular.getText().equals("")||
           jTextField_anios_edad.getText().equals("")||
           jTextField_numero_dni.getText().equals("")||
           jTextField_usuario.getText().equals("")||
           jPasswordField_contrasenia.getText().equals("")
          ){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
            
        }else {
            
        p.setId(ge.generaIds());
        p.setNombres(jTextField1_nombres.getText());
        p.setApellido_pater(jTextField_apellpater.getText());
        p.setApellido_mater(jTextField_apellmater.getText());
        p.setDireccion(jTextField_direccion.getText());
        p.setCorreo(jTextField_correo.getText());
        p.setNum_celular(jTextField_numero_celular.getText());
        p.setAnios_edad(jTextField_anios_edad.getText());
        p.setDni(jTextField_numero_dni.getText());
        p.setNivel_educacion(jComboBox_nivel_educacion.getSelectedItem());
        p.setEstado_civil(jComboBox_estado_civil.getSelectedItem());
        p.setGenero(jComboBox_genero.getSelectedItem());
        p.setUsuario(jTextField_usuario.getText());
        p.setContrasenia(jPasswordField_contrasenia.getText());

        ip.registrarPersona(p);
        
        JOptionPane.showMessageDialog(null, "Datos registrados con exito");
        AddOneReporteData();
        limpiarJTextField();
        
        }
        
        //Reporte por consola para verificar
        ip.reportePersonas();
        

    }//GEN-LAST:event_jButton_grabarActionPerformed

    private void jButton_Limpiar_AgregarPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Limpiar_AgregarPersonasActionPerformed
        
        limpiarJTextField();
        
    }//GEN-LAST:event_jButton_Limpiar_AgregarPersonasActionPerformed

    private void jTable1_reporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_reporteMouseClicked

    }//GEN-LAST:event_jTable1_reporteMouseClicked
    
    public void AddOneReporteData(){
        Utils u = new Utils();
        
         Object[] fila = new Object[14];
         fila[0]= jTextField_person_id.getText();
         fila[1]= jTextField1_nombres.getText();
         fila[2]= jTextField_apellpater.getText();
         fila[3]= jTextField_apellmater.getText();
         fila[4]= jTextField_direccion.getText();
         fila[5]= jTextField_correo.getText();
         fila[6]= jTextField_numero_celular.getText();
         fila[7]= jTextField_anios_edad.getText();
         fila[8]= jTextField_numero_dni.getText();
         fila[9]= jComboBox_nivel_educacion.getSelectedItem();
         fila[10]= jComboBox_estado_civil.getSelectedItem();
         fila[11]= jComboBox_genero.getSelectedItem();
         fila[12]= jTextField_usuario.getText();
         fila[13]= "********";
    
         modelo.addRow(fila);
         
         jTable1_reporte.setModel(modelo);
           
        
    }
    
    public void limpiarJTextField(){
       jTextField1_nombres.setText("");
       jTextField_apellpater.setText("");
       jTextField_apellmater.setText("");
       jTextField_direccion.setText("");
       jTextField_correo.setText("");
       jTextField_numero_celular.setText("");
       jTextField_anios_edad.setText("");
       jTextField_numero_dni.setText("");
       jTextField_usuario.setText("");
       jPasswordField_contrasenia.setText("");
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Limpiar_AgregarPersonas;
    private javax.swing.JButton jButton_grabar;
    private javax.swing.JComboBox<String> jComboBox_estado_civil;
    private javax.swing.JComboBox<String> jComboBox_genero;
    private javax.swing.JComboBox<String> jComboBox_nivel_educacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_apellpater;
    private javax.swing.JLabel jLabel1_nombres;
    private javax.swing.JLabel jLabel1_titulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_anios_edad;
    private javax.swing.JLabel jLabel_apellmater;
    private javax.swing.JLabel jLabel_contrasenia;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_direccion;
    private javax.swing.JLabel jLabel_numero_celular;
    private javax.swing.JLabel jLabel_numero_dni;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JPasswordField jPasswordField_contrasenia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_reporte;
    private javax.swing.JTextField jTextField1_nombres;
    private javax.swing.JTextField jTextField_anios_edad;
    private javax.swing.JTextField jTextField_apellmater;
    private javax.swing.JTextField jTextField_apellpater;
    private javax.swing.JTextField jTextField_correo;
    private javax.swing.JTextField jTextField_direccion;
    private javax.swing.JTextField jTextField_numero_celular;
    private javax.swing.JTextField jTextField_numero_dni;
    private javax.swing.JTextField jTextField_person_id;
    private javax.swing.JTextField jTextField_usuario;
    // End of variables declaration//GEN-END:variables
}
